"""for prese

Revision ID: 082781ace2f4
Revises: d192570ea797
Create Date: 2020-10-01 21:04:42.002152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082781ace2f4'
down_revision = 'd192570ea797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('belt_color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'belt_color')
    op.drop_column('comments', 'avatar')
    # ### end Alembic commands ###
