"""Add block modification

Revision ID: 615668cc992e
Revises: b076b4e329bd
Create Date: 2020-10-20 14:22:22.477830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615668cc992e'
down_revision = 'b076b4e329bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('blocks_blocked_id_fkey', 'blocks', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.create_foreign_key('blocks_blocked_id_fkey', 'blocks', 'users', ['blocked_id'], ['id'])
    op.drop_column('blocks', 'user_id')
    # ### end Alembic commands ###
