"""Add Password to Users

Revision ID: 7d1995d7276f
Revises: f3cf31745367
Create Date: 2020-09-14 11:12:08.755184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1995d7276f'
down_revision = 'f3cf31745367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_password', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_password')
    # ### end Alembic commands ###
